spring.application.name=angular-knowledge
spring.datasource.url=jdbc:postgresql://localhost:54321/angular-knowledge-db
spring.datasource.username=admin
spring.datasource.password=admin
spring.sql.init.mode=always

spring.output.ansi.enabled=ALWAYS
